routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Exports\UsersExport;
use App\Exports\TasksExport;
use App\Task;

Route::get('/', function () {
    return view('welcome');
});

// Reportes Excel
Route::get('excel', function () {
     return (new UsersExport)->download('users.xlsx');
});

Route::get('task_excel', function () {
     return (new TasksExport)->download('tareas.xlsx');
})->name('task.excel');

Route::get('table', function () {
     $tasks = Task::orderBy('created_at', 'asc')->get();
     return view('exports.tasks', compact('tasks'));
});


Auth::routes();

Route::get('municipios', 'CatJsonController@municipalitys')->name('municipalitys');

Route::get('localidades', 'CatJsonController@locations')->name('locations');

Route::get('code_postal', 'CatJsonController@code_postal')->name('code_postal');

Route::get('test', 'Admin\UserController@test')->name('test');


Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::post('/send_mail', 'AdminController@send_mail')->name('admin.send_mail');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('contact', 'ContacController', ['as' => 'admin']);
     Route::resource('postalcode', 'PostalCodeController', ['as' => 'admin']);
     Route::resource('task', 'TaskController', ['as' => 'admin']);
     Route::resource('type_policys', 'TypePolicysController', ['as' => 'admin']);
     Route::resource('requisition', 'RequisitionController', ['as' => 'admin']);
     Route::resource('notification_policy', 'NotificationPolicyController', ['as' => 'admin']);
     Route::resource('files_policys', 'FilesPolicysController', ['as' => 'admin']);

     Route::group(['prefix' => '{type_policy}'], function($group_id){
          Route::resource('policys', 'PolicysController', ['as' => 'admin']);
     });
     
     Route::post('user/{user}', 'UserController@update');
     Route::post('task/finish_task', 'TaskController@finish_task')->name('admin.task.finish_task');
     Route::post('task/advance_task', 'TaskController@advance_task')->name('admin.task.advance_task');
     Route::get('user/user_json/{user}', 'UserController@user_json')->name('admin.user.user_json');

});

app/NotificationPolicy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NotificationPolicy extends Model
{
    //
    protected $fillable = [
        "policie_id", "message", "file", 'created_by'
    ];

    public function creado_por()
    {
      return $this->hasOne( User::class, 'id', 'created_by' );
      
    }

}

app/Http/Controllers/Admin/NotificationPolicyController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\NotificationPolicy;
use Illuminate\Support\Facades\Storage;

use Auth;



class NotificationPolicyController extends Controller
{
    //
    public function index(Request $request)
    {
        $id =  request("id");
        $result = NotificationPolicy::where('policie_id', $id)->get();
        return response()->json($result->load('creado_por'));

    }

    public function store(Request $request)
    {

        $data = $request->validate([
              'message' => 'required',
              'policie_id' => 'required'
        ],[],[
               'message' => 'Nota',
        ]);

        if ($request->file('archivo') != null) {
            $nota = $request->file('archivo')->store('public');
            $data['file'] = Storage::url($nota);
       }

       $data['created_by'] = Auth::user()->id;

        $result = NotificationPolicy::create($data);

        return response()->json($result);

    }

    public function destroy(NotificationPolicy $notification_policy)
    {
         $notification_policy->delete();
        return response()->json($notification_policy);
    }
}

resources/views/admin/notification_policys/form.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_form_notificacion" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #2a7cf0; color: #fff;">
                <h5 class="modal-title">Formulario Notificacion<span></span></h5>
            </div>
            <div class="row" style="padding: 10px;">
                <div class="col-md-12">
                    <label for="nota">Nota</label>
                    <textarea class="form-control" id="message_modal" cols="30" rows="10"></textarea>
                </div>

                <div class="col-md-12">
                    <label for="archivo">Archivo</label>
                    <input type="file"  id="archivo">
                </div>

                <div class="col-md-12">
                    <hr>
                </div>

                <div class="col-6 text-left">
                    <button class="btn btn-sm btn-default" onclick="cancelar_form()"> Cancelar </button>
                </div>

                <div class="col-6 text-right">
                    <button class="btn btn-sm btn-success" onclick="guardar_modal()"> Guardar </button>
                </div>

            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script>
        function ver_modal_notificacion_form(id = false) {
            $('#modal_notificacion').modal('hide');
            $('#modal_form_notificacion').modal('show');
        }

        function guardar_modal(){
            var data = new FormData();
            var card_fiscal = $('#archivo')[0].files[0];
            data.append("archivo", card_fiscal);
            data.append('message', $('#message_modal').val());
            data.append('policie_id', policie_id);

            $.ajax({
                    processData: false,
                    contentType: false,
                    type: "POST",
                    dataType: "json",
                    url: "{{ route('admin.notification_policy.store') }}",
                    // url: "/admin/contacts/{{ $user->id }}",
                    data: data, // serializes the form's elements.
                    success: function(result) {
                         swal({
                              title: "Éxito",
                              text: 'Registrado correctamente',
                              type: 'success',
                              confirmButtonColor  : "#32c5d2",
                              confirmButtonText   : "Ok",
                              allowOutsideClick: false
                         }).then(function() {
                            $('#modal_form_notificacion').modal('hide');
                            ver_modal_notificacion(policie_id);
                         });
                    },
                    error:function(x,xs,xt){
                         var text = '';
                         var error_ret = x.responseJSON.errors;
                         $.each(error_ret, function(index, value) {
                              text += '<span class="strg">'+index + '</span> : '+ value[0] + '<br>';
                         });
                         swal({
                              title: "Error",
                              html: text,
                              type: 'error',
                         });
                    }
               });


        }

        function cancelar_form(){
            $('#modal_form_notificacion').modal('hide');

            $('#modal_notificacion').modal('show');
        }
    </script>

@endpush
@push('style')

@endpush

resources/views/admin/notification_policys/index.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_notificacion" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #2a7cf0; color: #fff;">
                <h5 class="modal-title">Notificación contacto<span></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="row" style="padding: 10px;">
                <div class="col-md-12 text-right">
                    <button class="btn btn-success btn-sm" onclick="ver_modal_notificacion_form()"> <i class="fa fa-plus" aria-hidden="true"></i> Agregar </button>
                    <br>
                    <br>
                </div>
                <div class="col-md-12">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Mensaje</th>
                                <th>Creador</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="table_notificacion">
                            <tr>
                                <td colspan="3" class="text-center">
                                    <i class='fas fa-spinner fa-spin fa-3x'></i>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                
                
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script>
        let policie_id = '';
        function ver_modal_notificacion(id) {
            policie_id = id;
            $('#table_notificacion').html(`<tr>
                                                <td colspan="3" class="text-center">
                                                    <i class='fas fa-spinner fa-spin fa-3x'></i>
                                                </td>
                                            </tr>`);
            $.ajax({
                url : "{{ route('admin.notification_policy.index') }}",
                data : { id : id },
                type : 'GET',
                dataType : 'json',
                success : function(json) {
                   if(json.length > 0){
                    $('#table_notificacion').html('');
                        json.forEach(function(elemento) {
                            let file = elemento.file ? `<a href="${elemento.file}" target="_blank" class="btn btn-sm btn-info"> <i class="fa fa-file" aria-hidden="true"></i> </a>` : '';
                            let btn_del =`<button onclick="eli_not(${elemento.id})" class="btn btn-sm btn-danger"> <i class="fa fa-trash" aria-hidden="true"></i> </button>`;
                            $( "#table_notificacion" ).append( `<tr>
                                                                    <td>${moment(elemento.created_at).format('MM/DD/YYYY')}</td>
                                                                    <td>${elemento.message}</td>
                                                                    <td>${elemento.creado_por.name} ${elemento.creado_por.last_name} ${elemento.creado_por.mother_last_name}</td>
                                                                    <td>${file} ${btn_del}</td>
                                                                </tr>` );
                        });
                   }else{
                        $('#table_notificacion').html(`<tr>
                                                <td colspan="3" class="text-center">
                                                    Sin resultados
                                                </td>
                                            </tr>`);
                   }
                },
                error : function(jqXHR, status, error) {
                    alert('Disculpe, existió un problema');
                },
                complete : function(jqXHR, status) {
                    $('#load_notificion').hide();
                }
            });
            $('#modal_notificacion').modal('show');
        }

        function eli_not(id){
            swal({
                title: "Eliminar",
                text: "¿ Desea eliminar ?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: '#DD6B55',
                confirmButtonText: 'Eliminar',
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                closeOnCancel: false
            }).then(function(res) {
                if(res.value){
                    $.ajax({
                        type: "DELETE",
                        dataType: "json",
                        url: "{{ url('admin/notification_policy/') }}/"+id,
                        // url: "/admin/contacts/{{ $user->id }}",
                        success: function(result) {
                            swal({
                                title: "Éxito",
                                text: 'Se elimino correctamente',
                                type: 'success',
                                confirmButtonColor  : "#32c5d2",
                                confirmButtonText   : "Ok",
                                allowOutsideClick: false
                            }).then(function() {
                                ver_modal_notificacion(policie_id);
                            });
                        },
                        error:function(x,xs,xt){
                            var text = '';
                            var error_ret = x.responseJSON.errors;
                            $.each(error_ret, function(index, value) {
                                text += '<span class="strg">'+index + '</span> : '+ value[0] + '<br>';
                            });
                            swal({
                                title: "Error",
                                html: text,
                                type: 'error',
                            });
                        }
                    });
                }
            });
        }
    </script>

@endpush
@push('style')

@endpush