routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Exports\UsersExport;
use App\Exports\TasksExport;
use App\Task;

Route::get('/', function () {
    return view('welcome');
});

// Reportes Excel
Route::get('excel', function () {
     return (new UsersExport)->download('users.xlsx');
});

Route::get('task_excel', function () {
     return (new TasksExport)->download('tareas.xlsx');
})->name('task.excel');

Route::get('table', function () {
     $tasks = Task::orderBy('created_at', 'asc')->get();
     return view('exports.tasks', compact('tasks'));
});


Auth::routes();

Route::get('municipios', 'CatJsonController@municipalitys')->name('municipalitys');

Route::get('localidades', 'CatJsonController@locations')->name('locations');

Route::get('code_postal', 'CatJsonController@code_postal')->name('code_postal');

Route::get('test', 'Admin\UserController@test')->name('test');


Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::post('/send_mail', 'AdminController@send_mail')->name('admin.send_mail');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('contact', 'ContacController', ['as' => 'admin']);
     Route::resource('postalcode', 'PostalCodeController', ['as' => 'admin']);
     Route::resource('task', 'TaskController', ['as' => 'admin']);
     Route::resource('type_policys', 'TypePolicysController', ['as' => 'admin']);
     Route::resource('requisition', 'RequisitionController', ['as' => 'admin']);
     Route::resource('notification_policy', 'NotificationPolicyController', ['as' => 'admin']);
     Route::resource('files_policys', 'FilesPolicysController', ['as' => 'admin']);

     Route::group(['prefix' => '{type_policy}'], function($group_id){
          Route::resource('policys', 'PolicysController', ['as' => 'admin']);
     });
     
     Route::post('user/{user}', 'UserController@update');
     Route::post('task/finish_task', 'TaskController@finish_task')->name('admin.task.finish_task');
     Route::post('task/advance_task', 'TaskController@advance_task')->name('admin.task.advance_task');
     Route::get('user/user_json/{user}', 'UserController@user_json')->name('admin.user.user_json');

});

app/Requisition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Requisition extends Model
{
    //
    protected $fillable = [
        "num", "policy_id" ,"endorsement_request","type_endorsement_id","way_pay_id","currency","initial_validity",
        "final_validity","receipt_expiration","yearly_fee","first_partiality","commission_currency","total_commission",
        "commission_percentage","movements","shipping_date","vehicle_key","vehicle_description","brand","sub_brand",
        "capacity","model","coverage","colour","engine_no","serial_number","re_na_ve","number_plates","vehicle_use",
        "preferred_beneficiary","regular_driver","service","type_load","double_trailer","with_load","special_team",
        "adaptations","technical_data", "creator_user"
   ];
 
   public function poliza()
   {
        return $this->hasOne( Policy::class, 'id', 'policy_id');
   }
   
   public function creado_por()
   {
        return $this->belongsTo( User::class, 'creator_user', 'id' );
   }


}

app/Http/Controllers/API/RequisitionController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Requisition;


class RequisitionController extends Controller
{
    //
    public function get_requisition_poilce(Request $request )
    {
        $requisitions = Requisition::where('policy_id', request('policy_id'))->get();
        return response()->json($requisitions->load('creado_por'));

    }
}

app/Http/Controllers/Admin/RequisitionController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Requisition;
use App\Policy;
use App\TypeEndorsement;
use App\TypeLoad;
use App\WayPay;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class RequisitionController extends Controller
{
    //
    public function index()
    {
        $requisitions = Requisition::all();
        $policys = Policy::all();
        return view('admin.requisition.index', compact('requisitions', 'policys'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
         
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {

         $data = $request->validate([
              'num' => 'required|string|max:255',
         ]);
         $data = request()->all();
         $data["creator_user"] = Auth::id(); 

         $requisition = Requisition::create($data);

         return redirect()->route('admin.requisition.index')->with('success', 'Endoso registrado');
    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show(Requisition $requisition)
    {
         $type_persons = TypePerson::all();
         $promoters = requisition::all();
         $sexs = Sex::all();
         $types_sellers = TypeSeller::all();
         $states = State::all();
         return view('admin.requisition.show', compact('requisition','type_persons', 'promoters', 'sexs', 'types_sellers', 'states'));
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit(Requisition $requisition)
    {
         $type_endorsements = TypeEndorsement::all();
         $way_pays = WayPay::all();
         $policys = Policy::all();
         $type_load = TypeLoad::all();
         return view('admin.requisition.edit', compact('requisition', 'type_endorsements', 'way_pays', 'policys', 'type_load'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, Requisition $requisition)
    {

         $data = request()->all();
         $data["initial_validity"] = request("initial_validity") != "" ? Carbon::createFromFormat('d-m-Y', request("initial_validity"))->format('Y-m-d') : NULL ;
         $data["final_validity"] = request("final_validity") != "" ? Carbon::createFromFormat('d-m-Y', request("final_validity"))->format('Y-m-d') : NULL ;
         $data["receipt_expiration"] = request("receipt_expiration") != "" ? Carbon::createFromFormat('d-m-Y', request("receipt_expiration"))->format('Y-m-d') : NULL ;
         $data["shipping_date"] = request("shipping_date") != "" ? Carbon::createFromFormat('d-m-Y', request("shipping_date"))->format('Y-m-d') : NULL ;

         $requisition->update( $data );

         return redirect()->route('admin.requisition.index')->with('success', 'Endoso actualizado');
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy(requisition $requisition)
    {
         
         $requisition->delete();
         return back()->with('success', 'Usuario eliminado');

    }

}

resources/views/admin/requisition/create.blade.php
@extends('admin.layout')

@section('content')
    <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
            <div class="card-header ">
                <h3 class="card-title">Registrar contacto</h3>
            </div>
            <div class="card-body">
                <div id="demo">
                    <div class="step-content">
                        <div class="step-tab-panel" id="tab1">
                            <form method="post" enctype="multipart/form-data" action="{{ route('admin.user.store') }}">
                                {{ csrf_field() }}
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Nombre(s) </label>
                                            <input type="text" name="name" value="{{ old('name') }}" class="form-control"
                                                required>
                                            @if ($errors->has('name'))
                                                <span class="error" role="alert">
                                                    <strong>{{ $errors->first('name') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Apellido paterno </label>
                                            <input type="text" name="last_name" value="{{ old('last_name') }}"
                                                class="form-control" required>
                                            @if ($errors->has('last_name'))
                                                <span class="error" role="alert">
                                                    <strong>{{ $errors->first('last_name') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Apellido materno </label>
                                            <input type="text" name="mother_last_name"
                                                value="{{ old('mother_last_name') }}" class="form-control">
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Correo *</label>
                                            <input type="email" name="email" value="{{ old('email') }}"
                                                class="form-control" required>
                                            @if ($errors->has('email'))
                                                <span class="error" role="alert">
                                                    <strong>{{ $errors->first('email') }}</strong>
                                                </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Fecha de nacimiento *</label>
                                            <input type="text" name="birthdate" value="{{ old('birthdate') }}"
                                                class="form-control datemask" data-inputmask-alias="datetime"
                                                data-inputmask-inputformat="dd/mm/yyyy" data-mask required>
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label>Sexo </label>
                                            <select class="form-control" name="sex_id">
                                                <option value="">-- Seleccione uno --</option>
                                                <?php foreach ($sexs as $key => $sex): ?>
                                                <option @if (old('sex_id') == $sex->id) selected @endif value="<?= $sex->id ?>"><?= $sex->name ?></option>
                                                          <?php endforeach; ?>
                                                     </select>
                                                </div>
                                           </div>

                                           <div class="col-md-4">
                                                <div class="form-group">
                                                     <label>Teléfono fijo</label>
                                                     <input type="text" name="phone" value="{{ old('phone') }}" class="form-control">
                                                </div>
                                           </div>

                                           <div class="col-md-4">
                                                <div class="form-group">
                                                     <label>Teléfono móvil *</label>
                                                     <input type="text" name="cell_phone" value="{{ old('cell_phone') }}"   class="form-control" required>
                                                </div>
                                           </div>

                                           <div class="col-md-4">
                                                 <label>Contraseña</label>
                                                 <input id="password-field" type="password" class="form-control" name="password" >
                                                 <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                            </div>
                                      </div>  
                                      <div class="row">
                                           <div class="col-md-6">
                                                 <a href="{{ route('admin.user.index') }}" class="btn btn-default"> <i class="fa fa-return" aria-hidden="true"></i> Regresar </a>
                                           </div>
                                           <div class="col-md-6 text-right">
                                                 <button type="submit" class="btn btn-success"> <i class="fa fa-save" aria-hidden="true"></i> Agregar </button>
                                           </div>
                                       </div>                                              
                                 </form>
                            </div>
                       </div>
                  </div>
             </div>
        </div>
    </div>

    @include('admin.postal_code.create_modal')


@stop
@push('scripts')
         <script src="{{ asset('/js/inputmask/min/jquery.inputmask.bundle.min.js') }}"></script>
         <script>
              $( document ).ready(function() {
                   $('.datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })

              });
              $(".toggle-password").click(function() {
                    $(this).toggleClass("fa-eye fa-eye-slash");
                    var input = $($(this).attr("toggle"));
                    if (input.attr("type") == "password") {
                         input.attr("type", "text");
                    } else {
                         input.attr("type", "password");
                    }
                });
         </script>
@endpush
@push('style')
    <style>
         .error{
              color:red;
              font-size: 13px;
         }
         .field-icon {
               float: right;
               margin-right: 10px;
               margin-top: -27px;
               position: relative;
               z-index: 2;
          }
    </style>
@endpush

resources/views/admin/requisition/index.blade.php
@extends('admin.layout')

@section('content')
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header ">
                <h3 class="card-title">Contactos</h3>
                <div class="card-tools">
                    <a href="#" data-toggle="modal" data-target="#modal_created" class="btn btn-success btn-sm">
                        <i class="fa fa-plus"></i> Nuevo
                    </a>
                </div>
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover table-striped table_js">
                    <thead>
                        <tr>
                            <th>Fecha de Emisión</th>
                            <th>Póliza</th>
                            <th>Asegurado</th>
                            <th>Endoso Numero.</th>
                            <th>Creado</th>
                            <th class="text-center"><i class="fas fa-cog"></i></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($requisitions as $requisition)
                            <tr>
                                <td class="text-center">{{ $requisition->created_at->format('d-m-Y')}}</td>
                                <td class="text-center">{{ $requisition->poliza->request_number }}</td>
                                <td class="text-center">{{ $requisition->poliza->asegurado->name }} {{ $requisition->poliza->asegurado->last_name }} {{ $requisition->poliza->asegurado->mother_last_name }}</td>
                                <td class="text-center">{{ $requisition->num }}</td>
                                <td lass="text-center">
                                    {{ $requisition->creado_por->name }} {{ $requisition->creado_por->last_name }} {{ $requisition->creado_por->mother_last_name }}
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('admin.requisition.edit', $requisition) }}"
                                        class="btn btn-sm btn-info btn-outline"><i class="fas fa-edit"></i></a>

                                    {{-- <form method="POST" action="{{ route('admin.requisition.destroy', $requisition) }}"
                                        style="display:inline">
                                        {{ csrf_field() }} {{ method_field('DELETE') }}
                                        <button class="btn btn-sm btn-danger btn-outline"
                                            onclick="return confirm('¿ Estás seguro de querer desactivar este contacto ?')">
                                            <i class="fas fa-trash"></i>
                                        </button>

                                    </form> --}}

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @include('admin.requisition.modal_new')
@stop

resources/views/admin/requisition/modal_lista.blade.php
<!-- Modal -->
<div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Eventos</h5>
                <a type="button" class="btn btn-success btn-sm" target="_black" href="<?=url('/admin/requisition')?>">
                    <i class="fas fa-plus"></i> Endoso
                </a>
            </div>
            <div class="modal-body" style="padding:0px;">
                <div class="row"  id="table_modal">
                    <div class="col-md-12">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>#ID</th>
                                    <th>Número Endoso</th>
                                    <th>Creado Por</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody id="table_endosos">
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="row" id="load_modal">
                    <div class="col-md-12 text-center" style="padding: 15px;">
                        <i class="fas fa-circle-notch fa-spin fa-5x"></i>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-info push-right" onclick="recargar()"> 
                    <i class="fa fa-retweet" aria-hidden="true"></i>
                    Recargar 
                </button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#exampleModal').on('show.bs.modal', event => {
        var button = $(event.relatedTarget);
        var modal = $(this);
        // Use above variables to manipulate the DOM
        
    });
</script>

resources/views/admin/requisition/modal_new.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_created" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #2a7cf0; color: #fff;">
                <h5 class="modal-title">Nuevo endoso <span></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" enctype="multipart/form-data" action="{{ route('admin.requisition.store') }}">
                {{ csrf_field() }}
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12 m-t-20">
                            <label for="">Solicitud de endoso</label>
                            <select class="form-control" name="policy_id" id="mod_policy" required>
                                    <option value=""> Selecciona una poliza </option>
                                    @foreach ($policys as $_policy)
                                        <option data-count=" {{ $_policy->endosos->count() }}" value="{{ $_policy->id }}">{{$_policy->request_number}}</option>
                                    @endforeach
                            </select>
                        </div>
                       
                        <div class="col-md-12">
                            <label for="">Num de endoso</label>
                            <input type="text" name="num" id="mod_num" value="" class="form-control"  required readonly>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
@push('style')

@endpush
@push('scripts')
    <script>
        $('#mod_policy').change(function(){
            if($(this).find(':selected').val() != ""){
                let num = $(this).find(':selected').attr('data-count');
                num++;
                $('#mod_num').val(num);
            }else{
                $('#mod_num').val('');
            }
        });
    </script>

@endpush