routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Exports\UsersExport;
use App\Exports\TasksExport;
use App\Task;

Route::get('/', function () {
    return view('welcome');
});

// Reportes Excel
Route::get('excel', function () {
     return (new UsersExport)->download('users.xlsx');
});

Route::get('task_excel', function () {
     return (new TasksExport)->download('tareas.xlsx');
})->name('task.excel');

Route::get('table', function () {
     $tasks = Task::orderBy('created_at', 'asc')->get();
     return view('exports.tasks', compact('tasks'));
});


Auth::routes();

Route::get('municipios', 'CatJsonController@municipalitys')->name('municipalitys');

Route::get('localidades', 'CatJsonController@locations')->name('locations');

Route::get('code_postal', 'CatJsonController@code_postal')->name('code_postal');

Route::get('test', 'Admin\UserController@test')->name('test');


Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::post('/send_mail', 'AdminController@send_mail')->name('admin.send_mail');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('contact', 'ContacController', ['as' => 'admin']);
     Route::resource('postalcode', 'PostalCodeController', ['as' => 'admin']);
     Route::resource('task', 'TaskController', ['as' => 'admin']);
     Route::resource('type_policys', 'TypePolicysController', ['as' => 'admin']);
     Route::resource('requisition', 'RequisitionController', ['as' => 'admin']);
     Route::resource('notification_policy', 'NotificationPolicyController', ['as' => 'admin']);
     Route::resource('files_policys', 'FilesPolicysController', ['as' => 'admin']);

     Route::group(['prefix' => '{type_policy}'], function($group_id){
          Route::resource('policys', 'PolicysController', ['as' => 'admin']);
     });
     
     Route::post('user/{user}', 'UserController@update');
     Route::post('task/finish_task', 'TaskController@finish_task')->name('admin.task.finish_task');
     Route::post('task/advance_task', 'TaskController@advance_task')->name('admin.task.advance_task');
     Route::get('user/user_json/{user}', 'UserController@user_json')->name('admin.user.user_json');

});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = [
        'name', 'email', 'password', 'type_person_id', 'promoter_id',
        'last_name', 'mother_last_name', 'stall', 'rfc', 'birthdate', 'sex_id', 'curp',
        'type_seller', 'state_id', 'municipality_id', 'location_id', 'street', 'n_ext',
        'n_int', 'phone', 'cell_phone', 'card_fiscal', 'identification_official',
        'voucher_home', 'minutes_constitutive', 'powers', 'business_folio', 'other',
        'postal_code', 'reference', 'passport', 'identification_official_validity', 'passport_validity',
        'status','notes', 'insured_grouo_id', 'executive_id', 'reference_user', 'business', 'occupation', 'insured_grouo', 'assigned_number'
   ];

   /**
   * The attributes that should be hidden for arrays.
   *
   * @var array
   */
   protected $hidden = [
        'password', 'remember_token',
   ];

   public function perfil()
   {
        return $this->belongsTo( TypeSeller::class, 'type_seller', 'id' );
   }

   public static function identification_official_expire()
   {
        return \DB::table('users')->where('identification_official_validity', '!=' , '0000-00-00')->WhereNotNull('identification_official_validity')->get();
   }

   public static function passport_expire()
   {
        return \DB::table('users')->where('passport_validity', '!=' , '0000-00-00')->WhereNotNull('passport_validity')->get();
   }

   public function contactos()
   {
        return $this->hasMany( InformationContact::class);
   }

   public function tareas_asignadas()
   {
        return $this->hasMany( Task::class, 'user_id', 'id' )->orderBy('created_at', 'desc');
   }

   public function tareas_pendientes()
   {
        return $this->hasMany( Task::class, 'user_id', 'id' )->where('tasks.status', '2');
   }

   public function tareas_asignadas_no_finalizadas()
   {
        return $this->hasMany( Task::class, 'user_id', 'id' )->where('tasks.status', '!=', '3')->orderBy('created_at', 'desc');
   }


   public function tareas_finalizadas()
   {
        return $this->hasMany( Task::class, 'user_id', 'id' )->where('tasks.status', '3');
   }

   public function facturacion()
   {
        return $this->hasMany( Billing::class );
   }

   public function grupo_asegurado()
   {
        return $this->belongsTo( InsuredGroup::class, 'insured_grouo_id', 'id');
   }

   public function direction_cp()
   {
        return $this->hasMany( PostalCode::class, 'id', 'location_id' );
   }

   public function polizas()
   {
          return $this->hasMany( Policy::class, 'contratante', 'id' );
   }
}

app/Http/Controllers/API/ContactController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Contact;


class ContactController extends Controller
{
    //

    public function contact(Request $request)
    {
        $contact = Contact::where('id', $request->id)->first();
        return response()->json($contact->load('direction_cp'));

    }
}

resources/views/admin/contact/index.blade.php
@extends('admin.layout')

@section('content')
<div class="col-md-12">
     <div class="card ">
          <div class="card-header ">
               <h3 class="card-title">Contactos</h3>
               <div class="card-tools">
                    <a href="{{ route('admin.contact.create') }}" class="btn btn-success btn-sm">
                         <i class="fa fa-plus"></i> Nuevo
                    </a>
               </div>
          </div>
          <div class="card-body table-responsive">
               <div class="row">
                    <div class="col-md-4"> 
                         <div class="bg-lightblue ui-draggable ui-draggable-handle text-center" style="background-color: #2959b3 !important; padding: 5px; border-radius: 4px;">
                              <div class="icheck-success d-inline">
                                   <input type="radio" id="checkboxPrimary1" name="type" value="all" class="radio" 
                                   @if(is_null($type) || $type == "all")
                                        checked
                                   @endif>
                                   <label for="checkboxPrimary1" style="margin-bottom: 0px; margin-left: 10px;">
                                        Todoso
                                   </label>
                              </div>
                         </div>
                    </div>
                    <div class="col-md-4"> 
                         <div class="bg-lightblue ui-draggable ui-draggable-handle text-center" style="background-color: #3ea556 !important; padding: 5px; border-radius: 4px;">
                              <div class="icheck-success d-inline">
                                   <input type="radio" id="checkboxPrimary2" name="type" value="1" class="radio"
                                   @if($type == "1")
                                        checked
                                   @endif>
                                   <label for="checkboxPrimary2" style="margin-bottom: 0px; margin-left: 10px;">
                                        Activos
                                   </label>
                              </div>
                         </div>
                    </div>
                    <div class="col-md-4"> 
                         <div class="bg-lightblue ui-draggable ui-draggable-handle text-center" style="background-color: #af444e !important; padding: 5px; border-radius: 4px;">
                              <div class="icheck-success d-inline">
                                   <input type="radio" id="checkboxPrimary3" name="type" value="2" class="radio"
                                   @if($type == "2")
                                        checked
                                   @endif>
                                   <label for="checkboxPrimary3" style="margin-bottom: 0px; margin-left: 10px;">
                                        Inactivos
                                   </label>
                              </div>
                         </div>
                    </div>
               </div>
               <br>
               <table class="table table-hover table-striped table_js">
                    <thead>
                         <tr>
                              <th>ID</th>
                              <th>Nombre</th>
                              <th>Grupo de asegurados</th>
                              <th>Teléfono</th>
                              {{-- <th>Correo</th> --}}
                              <th>Referencia de contacto</th>
                              <th>Polizas</th>
                              <th class="text-center">WhatsApp</th>
                              {{-- <th>Perfil Usuario</th> --}}
                              <th class="text-center">Enviar correo</th>
                              <th class="text-center"><i class="fas fa-cog"></i></th>
                         </tr>
                    </thead>
                    <tbody>
                         @foreach ($users as $user)
                         <tr>
                              <td>{{ $user->id }}</td>
                              <td>{{ $user->name }} {{ $user->last_name }} {{ $user->mother_last_name }}</td>
                              <td>
                                   {{ $user->insured_grouo }}
                              </td>                            
                              <td>{{ $user->cell_phone }}</td>
                              {{-- <td>{{ $user->email }}</td> --}}
                              <td>{{ $user->reference }}</td>
                              <td>
                                   @if (count($user->polizas) > 0)
                                        @foreach ($user->polizas as $polizas)
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                             <button class="btn btn-sm btn-default">
                                                  <i onclick="ver_modal_notificacion('{{ $polizas->id }}')" class="text-info fas fa-calendar"></i>
                                             </button>
                                             <a href="{{ url('admin/' . $polizas->type_policys_id . '/policys/' . $polizas->id . '') }}" target="_blank" class="btn btn-sm btn-default">
                                                  <i class="text-danger fas fa-file-pdf"></i>
                                                  {{ $polizas->request_number }}
                                             </a>
                                             @if ($polizas->vencimiento($polizas->vigencia_final) > 0)
                                                  @if ($polizas->vencimiento($polizas->vigencia_final) <= 30)
                                                       <button class="btn btn-sm btn-default">
                                                            <i class="text-warning fas fa-exclamation-triangle"></i>
                                                       </button>
                                                  @endif    
                                             @endif
                                             <button onclick="ver_modal_archivos('{{ $polizas->id }}', '{{ $user->cell_phone }}')" class="btn btn-sm btn-default">
                                                  <i class="fa fa-upload" aria-hidden="true"></i>
                                             </button>
                                        </div>
                                        @endforeach
                                   @endif
                              </td>
                              <td class="text-center">
                                   <?php if ($user->cell_phone): ?>
                                        <a href="https://api.whatsapp.com/send?phone=+52{{ $user->cell_phone }}" target="_blank" class="btn btn-success btn-sm"><i class="fab fa-whatsapp"></i></a>
                                   <?php endif; ?>
                              </td>
                              {{-- <td>{{ $user->perfil->name }}</td> --}}
                              <td class="text-center">
                                   <button type="button" class="btn btn-secondary btn-sm" onclick="ver_modal_mail('{{ $user->email }}')">
                                        <i class="fas fa-envelope-open-text"></i>
                                   </button>
                              </td>
                              <td class="text-center">

                                   <a href="{{ route('admin.contact.edit', $user) }}"
                                        class="btn btn-sm btn-info btn-outline"
                                   ><i class="fas fa-user-edit"></i></a>

                                   <form method="POST"
                                        action="{{ route('admin.contact.destroy', $user) }}"
                                        style="display:inline">
                                        {{ csrf_field() }} {{ method_field('DELETE') }}
                                        <?php if ($user->status == 1): ?>
                                             <button class="btn btn-sm btn-success btn-outline"
                                                  onclick="return confirm('¿ Estás seguro de querer desactivar este contacto ?')"
                                             >
                                                  <i class="fas fa-toggle-on"></i>
                                             </button>
                                        <?php else: ?>
                                             <button class="btn btn-sm btn-danger btn-outline"
                                                  onclick="return confirm('¿ Estás seguro de querer activar este contacto ?')"
                                             >
                                                  <i class="fas fa-toggle-off"></i>
                                             </button>
                                        <?php endif; ?>

                                   </form>
                                   @if ($user->tareas_asignadas_no_finalizadas->count() > 0)
                                        <button type="button" class="btn btn-primary btn-sm">
                                             TP <span class="badge badge-danger ml-2">{{ $user->tareas_asignadas_no_finalizadas->count() }}</span>
                                        </button>
                                   @endif
                              </td>
                         </tr>
                         @endforeach
                    </tbody>
               </table>
          </div>
     </div>
</div>
@include('admin.contact.modal_mail')
@include('admin.notification_policys.index')
@include('admin.notification_policys.form')
@include('admin.contact.modal_files')
@stop
@push('scripts')
<script>
     $(document).ready(function() {
       $('.radio').click(function () {
         let url = window.location.origin + '/admin/contact?type='+ $(this).val();
         window.location = url;

       });

   });
</script>

@endpush

resources/views/admin/contact/modal_files.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_file" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Archivos</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="row" id="archivo_cards">
                                
                            </div>
                          
                        </div>
                      </div>
                </div>
                <div class="col-md-12">
                    <label for="archivo">Archivo</label>
                    <input type="file"  id="archivo_policy">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script>
        let global_policie_id;

        function ver_modal_archivos(policie_id, number_tel){
            console.log(policie_id);
            console.log(number_tel);
            $('#archivo_cards').html(`<div class="text-center col-md-12">
                                                <i class='fas fa-spinner fa-spin fa-3x'></i>
                                            </div>`);
            $.ajax({
                processData: false,
                contentType: false,
                type: "GET",
                dataType: "json",
                url: "{{ route('admin.files_policys.index') }}?id="+policie_id,
                success: function(result) {
                    if(result.length > 0){
                    $('#archivo_cards').html('');
                    result.forEach(function(elemento) {
                            let url_file  = "{{url('/')}}"+elemento.file;
                            $( "#archivo_cards" ).append( `<div class="col-md-4">
                                    <div class="card text-center">
                                        <a href="${elemento.file}" target="_blank">
                                            <i class="fa fa-file fa-5x" style="margin: 0 auto; padding: 10px;" aria-hidden="true"></i>
                                            <p>${elemento.name}</p>
                                        </a>
                                        <br>
                                        <div class="row" style="margin:10px">
                                            <div class="col-6">
                                                <a href="https://api.whatsapp.com/send?phone=52${number_tel}&text=En el siguiente link podrás descargar el archivo ${url_file}" target="_blank" class="btn btn-success btn-block btn-sm"><i class="fab fa-whatsapp"></i></a>
                                            </div>
                                            <div class="col-6">
                                                <button class="btn btn-sm btn-block btn-danger" onclick="eliminar_archivo(${elemento.id})">
                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                            </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>` );
                        });
                   }else{
                        $('#archivo_cards').html(`<tr>
                                                <td colspan="3" class="text-center">
                                                    Sin archivos
                                                </td>
                                            </tr>`);
                   }
                },
                error:function(x,xs,xt){
                        
                }
            });

            global_policie_id = policie_id;
            $('#modal_file').modal('show');
        }

        function eliminar_archivo(id){
            swal({
                title: "Eliminar",
                text: "¿ Desea eliminar ?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: '#DD6B55',
                confirmButtonText: 'Eliminar',
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                closeOnCancel: false
            }).then(function(res) {
                if(res.value){
                    $.ajax({
                        type: "DELETE",
                        dataType: "json",
                        url: "{{ url('admin/files_policys/') }}/"+id,
                        // url: "/admin/contacts/{{ $user->id }}",
                        success: function(result) {
                            swal({
                                title: "Éxito",
                                text: 'Se elimino correctamente',
                                type: 'success',
                                confirmButtonColor  : "#32c5d2",
                                confirmButtonText   : "Ok",
                                allowOutsideClick: false
                            }).then(function() {
                                ver_modal_archivos(global_policie_id);
                            });
                        },
                        error:function(x,xs,xt){
                            var text = '';
                            var error_ret = x.responseJSON.errors;
                            $.each(error_ret, function(index, value) {
                                text += '<span class="strg">'+index + '</span> : '+ value[0] + '<br>';
                            });
                            swal({
                                title: "Error",
                                html: text,
                                type: 'error',
                            });
                        }
                    });
                }
            });
        }

        $('#archivo_policy').change(function(e) {
            var data = new FormData();
            let fileName = e.target.files[0];
            data.append("archivo", fileName);
            data.append("policie_id", global_policie_id);
            $.ajax({
                    processData: false,
                    contentType: false,
                    type: "POST",
                    dataType: "json",
                    url: "{{ route('admin.files_policys.store') }}",
                    data: data, // serializes the form's elements.
                    success: function(result) {
                         swal({
                              title: "Éxito",
                              text: 'Archivo registrado correctamente',
                              type: 'success',
                              confirmButtonColor  : "#32c5d2",
                              confirmButtonText   : "Ok",
                              allowOutsideClick: false
                         }).then(function() {
                            $('#archivo_policy').val('');
                            $('.bootstrap-filestyle input').val('');
                            ver_modal_archivos(global_policie_id);
                         });
                    },
                    error:function(x,xs,xt){
                         var text = '';
                         var error_ret = x.responseJSON.errors;
                         $.each(error_ret, function(index, value) {
                              text += '<span class="strg">'+index + '</span> : '+ value[0] + '<br>';
                         });
                         swal({
                              title: "Error",
                              html: text,
                              type: 'error',
                         });
                    }
               });

        });
    </script>
    
@endpush
@push('style')

@endpush

resources/views/admin/contact/modal_mail.blade.php
<!-- Modal -->
<div class="modal fade" id="modal_mail" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #2a7cf0; color: #fff;">
                <h5 class="modal-title">Enviar correo <span></span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="post" enctype="multipart/form-data" action="{{ route('admin.send_mail') }}">
                {{ csrf_field() }}
                <div class="modal-body">
                    <div class="row">
                        <input type="hidden" id="in_correo" name="correo" value="">
                        <div class="col-md-12">
                            <label for="">Correo :</label>
                            <p id="tx_correo"></p>
                        </div>
                        <div class="col-lg-12">
                            <label for="">Asunto correo</label>
                            <input type="text" name="subject" value="" class="form-control" placeholder="Asunto correo"
                                required>
                        </div>
                        <div class="col-lg-12" style="margin-top: 15px;">
                            <label for="">Copia oculta</label>
                            <input type="text" name="correo_oculto" value="" class="form-control"
                                placeholder="Ejemplo - contacto@aseguranzza.com, envio@aseguranzza.com">
                        </div>
                        <div class="col-lg-12" style="margin-top: 15px;">
                            <label for="">Cuerpo del correo</label>
                            <textarea name="content" class="form-control" rows="8" cols="80" required></textarea>
                        </div>
                        <div class="col-lg-12" style="margin-top: 15px;">
                            <label for="">Archivo adjunto</label><br>
                            <input type="file" name="file" data-name="file" class="filestyle"
                                data-buttonName="btn-primary" data-badgeName="badge-danger"
                                data-buttonText="Adjuntar archivo">
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

@push('scripts')
    <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.all.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-filestyle/2.1.0/bootstrap-filestyle.min.js"></script>
    <script>
        $(document).ready(function() {
            CKEDITOR.replace('content');
            $(":file").filestyle({
                buttonName: "btn-primary",
                buttonText: "Adjuntar archivo",
                badgeName: "badge-danger"
            });

            $('.buttonText').text('Adjuntar archivo');
        });

        function ver_modal_mail(mail) {
            $('#in_correo').val(mail);
            $('#tx_correo').text(mail);
            $('#modal_mail').modal('show');
        }


        $('.filestyle').on('change', function() {
            var FileSize = this.files[0].size / 1024 / 1024; // in MiB
            if (FileSize > 10) {
                swal({
                    title: "Error",
                    html: 'El tamaño del archivo supera los 10 MB permitidos',
                    type: 'error',
                });
                $(this).val(''); //for clearing with Jquery
            }
        });

    </script>

@endpush
@push('style')

@endpush