routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Exports\UsersExport;
use App\Exports\TasksExport;
use App\Task;

Route::get('/', function () {
    return view('welcome');
});

// Reportes Excel
Route::get('excel', function () {
     return (new UsersExport)->download('users.xlsx');
});

Route::get('task_excel', function () {
     return (new TasksExport)->download('tareas.xlsx');
})->name('task.excel');

Route::get('table', function () {
     $tasks = Task::orderBy('created_at', 'asc')->get();
     return view('exports.tasks', compact('tasks'));
});


Auth::routes();

Route::get('municipios', 'CatJsonController@municipalitys')->name('municipalitys');

Route::get('localidades', 'CatJsonController@locations')->name('locations');

Route::get('code_postal', 'CatJsonController@code_postal')->name('code_postal');

Route::get('test', 'Admin\UserController@test')->name('test');


Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'auth'],
function(){
     Route::get('/', 'AdminController@index')->name('dashboard');
     Route::post('/send_mail', 'AdminController@send_mail')->name('admin.send_mail');
     Route::resource('user', 'UserController', ['as' => 'admin']);
     Route::resource('contact', 'ContacController', ['as' => 'admin']);
     Route::resource('postalcode', 'PostalCodeController', ['as' => 'admin']);
     Route::resource('task', 'TaskController', ['as' => 'admin']);
     Route::resource('type_policys', 'TypePolicysController', ['as' => 'admin']);
     Route::resource('requisition', 'RequisitionController', ['as' => 'admin']);
     Route::resource('notification_policy', 'NotificationPolicyController', ['as' => 'admin']);
     Route::resource('files_policys', 'FilesPolicysController', ['as' => 'admin']);

     Route::group(['prefix' => '{type_policy}'], function($group_id){
          Route::resource('policys', 'PolicysController', ['as' => 'admin']);
     });
     
     Route::post('user/{user}', 'UserController@update');
     Route::post('task/finish_task', 'TaskController@finish_task')->name('admin.task.finish_task');
     Route::post('task/advance_task', 'TaskController@advance_task')->name('admin.task.advance_task');
     Route::get('user/user_json/{user}', 'UserController@user_json')->name('admin.user.user_json');

});

app/PostalCode.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PostalCode extends Model
{
     public $timestamps = false;
    //
    protected $fillable = [
        'estado_id', 'estado','municipio_id', 'municipio', 'ciudad', 'colonia', 'cp'
   ];
}

app/Http/Controllers/Admin/PostalCodeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Response;
use App\Rules\PostalCodeValidation;
use App\PostalCode;


class PostalCodeController extends Controller
{

     public function store(Request $request)
     {
          $data = $request->validate([
               'codigo_postal' => ['required','digits:5',new PostalCodeValidation($request)],
               'nombre_colonia' => 'required'
          ]);

          if(request('municipality_modal_id') == 'otro') {
               $data =  $request->validate([
                    'nombre_ciudad' => 'required'
               ]);
          }

          $data["estado_id"] = request("state_modal_id");
          $estado = PostalCode::where('estado_id', request("state_modal_id"))->first();
          $data["estado"] = $estado->estado;

          if (request("municipality_modal_id") == 'otro') {
               $max_mun = PostalCode::max('municipio_id');
               $data["municipio_id"] = $max_mun+1;
               $data["municipio"] = request("nombre_ciudad");
          }else {
               $postal_code = PostalCode::where('estado_id', request("state_modal_id"))->where('municipio_id', request("municipality_modal_id"))->first();
               $data["municipio_id"] = request("municipality_modal_id");
               $data["municipio"] = $postal_code->municipio;     
          }

          $data["colonia"] = request("nombre_colonia");
          $data["cp"] = request("codigo_postal");

          $postal_code =  PostalCode::create($data);

          return Response::json($postal_code);

     }

}

resources/views/admin/postal_code/create_modal.blade.php
<div class="modal fade" id="modal-default">
     <div class="modal-dialog">
          <div class="modal-content">
               <div class="modal-header">
                    <h4 class="modal-title">Agregra dirección C.P.</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                         <span aria-hidden="true">&times;</span>
                    </button>
               </div>
               <form  action="{{ route('admin.postalcode.store') }}" method="post" id="FormCP">
                    <div class="modal-body">
                         <div class="row">
                              <div class="col-md-12">
                                   <div class="form-group">
                                        <label>C.P.</label>
                                        <input class="form-control" type="text" name="codigo_postal" value="">
                                   </div>
                              </div>
                              <div class="col-md-12">
                                   <div class="form-group">
                                        <label>Estado</label>
                                        <select class="form-control" name="state_modal_id" id="state_modal_id" onchange="get_municipios(this)" required>
                                             <?php foreach ($states as $key => $state) : ?>
                                                  <option value="<?=$state->estado_id ?>"><?=$state->estado ?></option>
                                             <?php endforeach; ?>
                                        </select>
                                   </div>
                              </div>
                              <div class="col-md-12">
                                   <div class="form-group">
                                        <label>Ciudad</label>
                                        <select class="form-control" name="municipality_modal_id" id="municipality_modal_id" onchange="get_localidad(this)" required>
                                             <?php foreach ($municipalitys as $key => $municipality) : ?>
                                                  <option value="<?=$municipality->municipio_id ?>"><?=$municipality->municipio ?></option>
                                             <?php endforeach; ?>
                                             <option value="otro">Otro</option>
                                        </select>
                                   </div>
                              </div>
                              <div class="col-md-12" id="div_nueva_ciudad" style="display:none;">
                                   <div class="form-group">
                                        <label>Nombre Ciudad</label>
                                        <input class="form-control" type="text" name="nombre_ciudad" id="nombre_ciudad" value="" >
                                   </div>
                              </div>
                              <div class="col-md-12">
                                   <div class="form-group">
                                        <label>Colonia</label>
                                        <input class="form-control" type="text" name="nombre_colonia" value="">
                                   </div>
                              </div>
                         </div>
                    </div>
                    <div class="modal-footer justify-content-between">
                         <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                         <button type="submit" class="btn btn-primary">Guardar dirección</button>
                    </div>
               </form>
          </div>
          <!-- /.modal-content -->
     </div>
     <!-- /.modal-dialog -->
</div>
@push('scripts')
<script>
$("#FormCP").submit(function(e) {

     e.preventDefault(); // avoid to execute the actual submit of the form.

     var form = $(this);
     var url = form.attr('action');

     $.ajax({
          type: "POST",
          url: url,
          data: form.serialize(), // serializes the form's elements.
          success: function(result) {
               console.log(result);
               swal({
                    title: "Éxito",
                    text: 'Registrado correctamente',
                    type: 'success',
                    confirmButtonColor  : "#32c5d2",
                    confirmButtonText   : "Ok",
                    allowOutsideClick: false
               }).then(function() {
                    $('#FormCP')[0].reset();
                    $('#modal-default').modal('hide');
               });
          },
          error:function(x,xs,xt){
               var text = '';
               var error_ret = x.responseJSON.errors;
               $.each(error_ret, function(index, value) {
                    text += value[0] + '<br>';
               });
               swal({
                    title: "Error",
                    html: text,
                    type: 'error',
               });
          }
     });


});

</script>
@endpush